### ISSUE TITLE
依赖库的版本号

### ISSUE THREAD

**Issue by xxllp** [heiheiyoyo/uie_pytorch#12]
请问下transformers等库的版本

**Comment by heiheiyoyo** [comment]
更新了requirements.txt

**Comment by xxllp** [comment]
这块uie相关的评论 情感分类的模型 是否也可以转换过来

**Comment by heiheiyoyo** [comment]
paddle中的uie和uie-m的模型都可以通过convert.py转换，可能需要调整一下convert.py中的代码
`python convert.py -i path/to/your/paddle_model -o path/to/output_model`

[`436            if 'uie-m' in args.input_model:`](https://github.com/heiheiyoyo/uie_pytorch/blob/main/convert.py#L436)
目前判断输入的Paddle模型的类型是通过字符串来判断的，可能需要修改。
