### ISSUE TITLE
数据预处理格式 - 关系抽取和事件抽取

### ISSUE THREAD

**Issue by disperaller** [heiheiyoyo/uie_pytorch#34]
请问下 关系抽取和事件抽取的微调数据的格式是一样的吗？都如下图？
![image](https://github.com/HUSTAI/uie_pytorch/assets/13672297/74edb0da-0d6e-4af5-b5ad-863e3e28b9cd)

不同点是不是事件抽取的entities会有一个trigger word，然后relations里面全部都是这个trigger word为from_id，其余角色为to_id?
然后关系抽取的entities里面可能就没有trigger word, 然后relations里面就纯粹是不同角色的关系？

**Comment by Jxh99** [comment]
@disperaller 您好，解决了吗？

**Comment by disperaller** [comment]
> @disperaller 您好，解决了吗？

嗯 后来解决了 这个issue我关了

**Comment by Jxh99** [comment]
@disperaller 嗯嗯，求问，在这个项目中，关系抽取和事件抽取的格式就是一致的哈？只是对于relation的映射关系可能会有差别对吧？

**Comment by disperaller** [comment]
> @disperaller 嗯嗯，求问，在这个项目中，关系抽取和事件抽取的格式就是一致的哈？只是对于relation的映射关系可能会有差别对吧？

对的
